module.exports = [
    { name: 'UTC', value: 'Z' },
    { name: 'US Eastern Time (EST)', value: '-05:00' },
    { name: 'US Eastern Daylight Time (EDT)', value: '-04:00' },
    { name: 'US Central Time (CST)', value: '-06:00' },
    { name: 'US Central Daylight Time (CDT)', value: '-05:00' },
    { name: 'US Mountain Time (MST)', value: '-07:00' },
    { name: 'US Mountain Daylight Time (MDT)', value: '-06:00' },
    { name: 'US Pacific Time (PST)', value: '-08:00' },
    { name: 'US Pacific Daylight Time (PDT)', value: '-07:00' },
    { name: 'British Summer Time (BST)', value: '+01:00' },
    { name: 'Greenwich Mean Time (GMT)', value: 'Z' },
    { name: 'Central European Time (CET)', value: '+01:00' },
    { name: 'Central European Summer Time (CEST)', value: '+02:00' },
    { name: 'Eastern European Time (EET)', value: '+02:00' },
    { name: 'Eastern European Summer Time (EEST)', value: '+03:00' },
    { name: 'Moscow Standard Time (MSK)', value: '+03:00' },
    { name: 'India Standard Time (IST)', value: '+05:30' },
    { name: 'China Standard Time (CST)', value: '+08:00' },
    { name: 'Japan Standard Time (JST)', value: '+09:00' },
    { name: 'Australian Eastern Standard Time (AEST)', value: '+10:00' },
    { name: 'Australian Eastern Daylight Time (AEDT)', value: '+11:00' },
    { name: 'New Zealand Standard Time (NZST)', value: '+12:00' },
    { name: 'New Zealand Daylight Time (NZDT)', value: '+13:00' },
    { name: 'Hawaii-Aleutian Standard Time (HST)', value: '-10:00' },
    { name: 'Alaska Standard Time (AKST)', value: '-09:00' },
    { name: 'Alaska Daylight Time (AKDT)', value: '-08:00' },
    { name: 'Atlantic Standard Time (AST)', value: '-04:00' },
    { name: 'Atlantic Daylight Time (ADT)', value: '-03:00' },
    { name: 'Brazil Standard Time (BRT)', value: '-03:00' },
    { name: 'Argentina Standard Time (ART)', value: '-03:00' },
    { name: 'West Africa Time (WAT)', value: '+01:00' },
    { name: 'South Africa Standard Time (SAST)', value: '+02:00' },
    { name: 'Arabia Standard Time (AST)', value: '+03:00' },
    { name: 'Pakistan Standard Time (PKT)', value: '+05:00' },
    { name: 'Bangladesh Standard Time (BST)', value: '+06:00' },
    { name: 'Indochina Time (ICT)', value: '+07:00' },
    { name: 'Philippine Standard Time (PST)', value: '+08:00' },
    { name: 'Korea Standard Time (KST)', value: '+09:00' },
    { name: 'Australian Central Standard Time (ACST)', value: '+09:30' },
    { name: 'Australian Central Daylight Time (ACDT)', value: '+10:30' },
    { name: 'Australian Western Standard Time (AWST)', value: '+08:00' },
  ];